from tools_shared_variables import META_DB_PATH
import duckdb

mdb = duckdb.connect(META_DB_PATH)

# define benchmark metrics table
def init_bench_metrics(mdb):
    mdb.execute('''
    CREATE TABLE IF NOT EXISTS cat_bench_metrics(
        huc STRING,
        version STRING,
        benchmark_data_cat STRING,
        lid STRING,
        magnitude STRING,
        benchmark_raster_path STRING,
        predicted_raster_path STRING,
        agreement_raster STRING,
        false_negatives_count DOUBLE,
        false_positives_count DOUBLE,
        true_negatives_count DOUBLE,
        true_positives_count DOUBLE,
        ACC DOUBLE,
        Bal_ACC DOUBLE,
        CSI DOUBLE,
        EQUITABLE_THREAT_SCORE DOUBLE,
        F1_SCORE DOUBLE,
        FAR DOUBLE,
        PND DOUBLE,
        FALSE_OMISSION_RATE DOUBLE,
        FALSE_POSITIVE_RATE DOUBLE,
        FOWLKES_MALLOW_INDEX DOUBLE,
        MCC DOUBLE,
        NEGATIVE_LIKELIHOOD_RATIO DOUBLE,
        NPV DOUBLE,
        BIAS DOUBLE,
        POSITIVE_LIKELIHOOD_RATIO DOUBLE,
        PPV DOUBLE,
        PREVALENCE DOUBLE,
        PREVALENCE_THRESHOLD DOUBLE,
        TNR DOUBLE,
        TPR DOUBLE,
        contingency_tot_count DOUBLE,
        TP_perc DOUBLE,
        FP_perc DOUBLE,
        TN_perc DOUBLE,
        FN_perc DOUBLE,
        cell_area_m2 DOUBLE,
        TP_area_km2 DOUBLE,
        FP_area_km2 DOUBLE,
        TN_area_km2 DOUBLE,
        FN_area_km2 DOUBLE,
        contingency_tot_area_km2 DOUBLE,
        predPositive_area_km2 DOUBLE,
        predNegative_area_km2 DOUBLE,
        obsPositive_area_km2 DOUBLE,
        obsNegative_area_km2 DOUBLE,
        positiveDiff_area_km2 DOUBLE,
        masked_count DOUBLE,
        masked_perc DOUBLE,
        masked_area_km2 DOUBLE,
        predPositive_perc DOUBLE,
        predNegative_perc DOUBLE,
        obsPositive_perc DOUBLE,
        obsNegative_perc DOUBLE,
        positiveDiff_perc DOUBLE
    )''')
